// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Kj7kZxA-kodzkG5nSp1rpzBsc8y5-ko',
    appId: '1:358683122878:android:8410897524c5cd738852ef',
    messagingSenderId: '358683122878',
    projectId: 'album-biblio-1d2e5',
    storageBucket: 'album-biblio-1d2e5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtGoByrYOfvtuqoHklCo32YrQfVYeKKcs',
    appId: '1:358683122878:web:1d5583a0e36542708852ef',
    messagingSenderId: '358683122878',
    projectId: 'album-biblio-1d2e5',
    authDomain: 'album-biblio-1d2e5.firebaseapp.com',
    storageBucket: 'album-biblio-1d2e5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtGoByrYOfvtuqoHklCo32YrQfVYeKKcs',
    appId: '1:358683122878:web:1d5583a0e36542708852ef',
    messagingSenderId: '358683122878',
    projectId: 'album-biblio-1d2e5',
    authDomain: 'album-biblio-1d2e5.firebaseapp.com',
    storageBucket: 'album-biblio-1d2e5.firebasestorage.app',
  );

}